name: Tests and Checks

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.4'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install project
        run: poetry install --no-interaction
      - name: Precommits
        run: |
          poetry run pre-commit install
          poetry run pre-commit run --all-files
      - name: Run tests
        run: |
          source .venv/bin/activate
          poetry run python -m pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=typerspace-api src/tests/unit
      - name: Coverage
        uses: MishaKav/pytest-coverage-comment@main
        with:
          junitxml-path: ./pytest.xml
